---
- hosts: elasticsearch
  gather_facts: no 
  remote_user: root
  ignore_errors: yes
  roles:
    - elasticsearch
  vars:
    - baseDir: /home/smartmining
    - AnsibleDir: /etc/ansible
    - elasticsearchVersion: elasticsearch-6.3.1
    - nodeip1: 192.168.0.177
    - nodeip2: 192.168.0.178
    - nodeip3: 192.168.0.179

