---
- hosts: redis
  gather_facts: no 
  remote_user: root
  ignore_errors: yes
  roles:
    - redis
  vars:
    - baseDir: /home/smartmining
    - AnsibleDir: /etc/ansible
    - redisVersion: redis-5.0.5
    - nodeip1: 192.168.0.177 
    - nodeip2: 192.168.0.178
    - nodeip3: 192.168.0.179 

